[package]

name = "linked_hash_map"
version = "0.0.2"
license = "MIT/Apache-2.0"
description = "A HashMap wrapper that holds key-value pairs in insertion order"
authors = [
    "Stepan Koltsov <stepan.koltsov@gmail.com>",
    "Andrew Paseltiner <apaseltiner@gmail.com>",
]

repository = "https://github.com/xwb1989/linked_hash_map"
homepage = "https://github.com/contain-rs/linked-hash-map"
documentation = "https://contain-rs.github.io/linked-hash-map/linked_hash_map"
keywords = ["data-structures"]
readme = "README.md"
